import type { InterviewPreset } from './types';

export const ALL_SECTION_IDS = [
  'javascript',
  'typescript',
  'html-css',
  'react',
  'vue',
  'nuxt',
  'nextjs',
  'testing',
  'performance',
  'architecture',
  'state-management',
  'api-communication',
  'build-and-deployment',
  'security',
  'ai',
] as const;

export const PRESETS: InterviewPreset[] = [
  {
    id: 'react-stack',
    title: 'React-стек',
    description: 'React, TypeScript и хранилища состояния',
    sections: ['react', 'typescript', 'state-management'],
    count: 20,
  },
  {
    id: 'js-core',
    title: 'Основы JavaScript',
    description: 'JavaScript, TypeScript и HTML/CSS',
    sections: ['javascript', 'typescript', 'html-css'],
    count: 30,
  },
  {
    id: 'basics',
    title: 'Основы веб-разработки',
    description: 'JavaScript и HTML/CSS',
    sections: ['javascript', 'html-css'],
    count: 10,
  },
  {
    id: 'vue',
    title: 'Vue-стек',
    description: 'Vue, Nuxt, TypeScript и хранилища состояния',
    sections: ['vue', 'nuxt', 'typescript', 'state-management'],
    count: 20,
  },
  {
    id: 'next',
    title: 'Next.js full-stack',
    description: 'Next.js, API, деплой и безопасность',
    sections: ['nextjs', 'api-communication', 'build-and-deployment', 'security'],
    count: 20,
  },
  {
    id: 'senior',
    title: 'Сеньор / архитектура',
    description: 'Архитектура, производительность и CI/CD',
    sections: ['architecture', 'performance', 'build-and-deployment', 'security'],
    count: 20,
  },
  {
    id: 'testing',
    title: 'Тестирование',
    description: 'Юнит-тесты, e2e и инфраструктура тестов',
    sections: ['testing', 'performance', 'build-and-deployment'],
    count: 15,
  },
  {
    id: 'ai',
    title: 'AI-разработка',
    description: 'AI в работе фронтендера, безопасность и API',
    sections: ['ai', 'security', 'api-communication'],
    count: 15,
  },
  {
    id: 'security',
    title: 'Безопасность',
    description: 'Безопасность и работа с API',
    sections: ['security', 'api-communication'],
    count: 15,
  },
  {
    id: 'full-frontend',
    title: 'Полный фронтенд',
    description: 'Все разделы Prepra',
    sections: [...ALL_SECTION_IDS],
    count: 50,
  },
];