import type { InterviewPreset } from './types';

export const ALL_SECTION_IDS = [
  'javascript',
  'typescript',
  'html-css',
  'react',
  'vue',
  'nuxt',
  'nextjs',
  'testing',
  'performance',
  'architecture',
  'state-management',
  'api-communication',
  'build-and-deployment',
  'security',
  'ai',
] as const;

export const PRESETS: InterviewPreset[] = [
  {
    id: 'web-basics',
    title: 'Основы веб-разработки',
    description: 'HTML/CSS, JavaScript и TypeScript',
    sections: ['html-css', 'javascript', 'typescript'],
    count: 30,
  },
  {
    id: 'react-stack',
    title: 'React-стек',
    description: 'React, TypeScript, хранилища и API',
    sections: ['react', 'typescript', 'state-management', 'api-communication'],
    stacks: ['react'],
    mainSection: 'react',
    count: 50,
  },
  {
    id: 'vue-stack',
    title: 'Vue-стек',
    description: 'Vue, TypeScript, хранилища и API',
    sections: ['vue', 'typescript', 'state-management', 'api-communication'],
    stacks: ['vue'],
    mainSection: 'vue',
    count: 50,
  },
  {
    id: 'next-fullstack',
    title: 'Next.js Full-stack',
    description: 'Next.js, API, CI/CD и безопасность',
    sections: ['nextjs', 'api-communication', 'build-and-deployment', 'security'],
    stacks: ['nextjs'],
    mainSection: 'nextjs',
    count: 50,
  },
  {
    id: 'nuxt-fullstack',
    title: 'Nuxt Full-stack',
    description: 'Nuxt, API, CI/CD и безопасность',
    sections: ['nuxt', 'api-communication', 'build-and-deployment', 'security'],
    stacks: ['nuxt'],
    mainSection: 'nuxt',
    count: 50,
  },
  {
    id: 'testing',
    title: 'Тестирование',
    description: 'Unit, E2E, пирамида и стратегии',
    sections: ['testing'],
    count: 30,
  },
  {
    id: 'performance',
    title: 'Производительность',
    description: 'Оптимизация, Core Web Vitals и рендеринг',
    sections: ['performance', 'javascript'],
    count: 30,
  },
  {
    id: 'architecture',
    title: 'Проектирование',
    description: 'Паттерны, архитектура и деплой',
    sections: ['architecture', 'build-and-deployment'],
    count: 30,
  },
  {
    id: 'ai',
    title: 'AI и LLM',
    description: 'LLM, RAG и AI-фичи во фронтенде',
    sections: ['ai'],
    mainSection: 'ai',
    count: 50,
  },
];
